server:
  servlet:
    context-path: /api/v1
  port: 8002

spring:
  mail:
    username: PublicMember@yqxc.info
    password: pz8wqe7JqPZeqhuB
    host: smtp.exmail.qq.com

  data:
    redis:
      repositories:
        enabled: false

  redis:
    #host: 123.57.237.249
    host: 18.142.168.39
    port: 6377
    password: Yijiang2021
    #Redis数据库索引（默认为0）
    database: 0
    timeout: 30000
    maxTotal: 30
    maxIdle : 10
    maxWaitMillis: 1500
    blockWhenExhausted: false
    JmxEnabled: true
    jedis:
      pool:
        max-active: 50  #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20    #连接池中的最大空闲连接
        min-idle: 2     #连接池中的最小空闲连接
      #连接超时时间（毫秒）
      timeout: 5000

  application:
    name: springboot-jwt
  #配置文件传输
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      # 上传文件总的最大值
      max-request-size: 100MB
      # 单个文件的最大值
      max-file-size: 100MB

config:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    show-sql: true
  token:
    secret: abcdefg1234567  # 加密密钥
    expire: 2592000            # token有效时长--30天
    header: userToken           # header 名称
  captcha:
    # 加密密钥
    secret: 1234567abcdefg
    # token有效时长
    expire: 120
    # header 名称
    header: kaptcha
  sms:
    secret: qwertyu321654987
    expire: 300
    header: sms_token
  mail:
    secret: qwertyu321654987
    expire: 300
    header: sms_token

icbc:
  MY_PRIVATE_KEY: "xxx"
  MY_PUBLIC_KEY : "xxx"
  APIGW_PUBLIC_KEY_GENERAL_BANK : "xxx"
  APIGW_PUBLIC_KEY_BEIJING_SUB : "xxx"
  APPID : "xxx"
  BASE_URL : "xxx"
  AES_KEY : "xxx"
  PROJECT_ID : "xxx"
  CORP_CIS : "xxx"
  flag : "success"

#fisco:
#  peers: "123.57.237.249:20200"
#  certPath: "conf"
#  hexPrivateKey:
#  groupId : 1
#  contract:
#    nftAddress: "0x67b0fa958deba6296508b3fba5a734e3e091fa93"
#  webaseUrl: "http://123.57.237.249:5002/WeBASE-Front/trans/signed-transaction"

#sms:
#  secretId: "AKIDQgfNq42jAKDo9E2arte8LHxNWOzJM7cm"
#  secretKey: "vZw2rPhhQs3ybx2qOghRu61e06uRiiQr"
#  SmsSdkAppid: "1400566775"
#  TemplateID: "1098940"
#  Signature: "FolkSpace"

sms:
  secretId: "xxx"
  secretKey: "xxx"
  SmsSdkAppid: "xxx"
  TemplateID: "xxx"
  Signature: "奕江科技"

blockchain:
  id: "ff60c023dd10c1db5cba4c9cf8be76634bafd07811062ad39c13ef579061219f"

com:
  mail:
    title:    "注册验证码"
    identity: "奕江科技"
    from : PublicMember@yqxc.info
    username: PublicMember@yqxc.info
    password: pz8wqe7JqPZeqhuB
    host: smtp.exmail.qq.com

platform:
  private_key: "7233ac0f2ded9719b828cb495d8ca2d90c5e6c36f49b9771331bc9274f138fc2"
  public_key : "04c0222cf005ae811aa214d9b98733f6f813a6ac63facb1d8ecee0d7f633b7c04be4600c971c6b9030e80bd5ac84c1ecac38de6f485a809dabec3698a877acbc30"
  address: "0xd1f6f665ea45aca059ffb2a24b28e092016b2045"

swagger:
  config:
    basePackage: com.betswap.market.adapter
    title: Betswap API Document.
    description: Provide Betswap relasted interface.
    version: 1.0

wechat:
  app_id: wx27f3f14d55e5ab22
  app_secret : 908b66777d552402a45bf2334552bfee
  redirect_url : www.folkspace.cn

user:
  default:
    avatar: /images/cover/default/avatar.png

auction_rule:
#  payTime:   259200000 #尾款支付时间
#
#  baseRange: 1999  #起步区间
#  baseDeposit: 100 #起步区间保证金
#  changeStep: 1000 #阶梯区间
#  stepDeposit: 100 #阶梯区间保证金
  payTime:   259200000 #尾款支付时间

  baseRange: 1999  #起步区间
  baseDeposit: 100 #起步区间保证金
  changeStep: 1000 #阶梯区间
  stepDeposit: 100 #阶梯区间保证金

#  switch:   是否开启日志开关
log:
    switch: false
